// Code generated by protoc-gen-go. DO NOT EDIT.
// source: types/types.proto

package types

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Age struct {
	Ticks                uint64   `protobuf:"varint,1,opt,name=ticks,proto3" json:"ticks,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Age) Reset()         { *m = Age{} }
func (m *Age) String() string { return proto.CompactTextString(m) }
func (*Age) ProtoMessage()    {}
func (*Age) Descriptor() ([]byte, []int) {
	return fileDescriptor_2c0f90c600ad7e2e, []int{0}
}

func (m *Age) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Age.Unmarshal(m, b)
}
func (m *Age) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Age.Marshal(b, m, deterministic)
}
func (m *Age) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Age.Merge(m, src)
}
func (m *Age) XXX_Size() int {
	return xxx_messageInfo_Age.Size(m)
}
func (m *Age) XXX_DiscardUnknown() {
	xxx_messageInfo_Age.DiscardUnknown(m)
}

var xxx_messageInfo_Age proto.InternalMessageInfo

func (m *Age) GetTicks() uint64 {
	if m != nil {
		return m.Ticks
	}
	return 0
}

type Config struct {
	Options              *PrimitiveMap `protobuf:"bytes,1,opt,name=options,proto3" json:"options,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *Config) Reset()         { *m = Config{} }
func (m *Config) String() string { return proto.CompactTextString(m) }
func (*Config) ProtoMessage()    {}
func (*Config) Descriptor() ([]byte, []int) {
	return fileDescriptor_2c0f90c600ad7e2e, []int{1}
}

func (m *Config) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Config.Unmarshal(m, b)
}
func (m *Config) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Config.Marshal(b, m, deterministic)
}
func (m *Config) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Config.Merge(m, src)
}
func (m *Config) XXX_Size() int {
	return xxx_messageInfo_Config.Size(m)
}
func (m *Config) XXX_DiscardUnknown() {
	xxx_messageInfo_Config.DiscardUnknown(m)
}

var xxx_messageInfo_Config proto.InternalMessageInfo

func (m *Config) GetOptions() *PrimitiveMap {
	if m != nil {
		return m.Options
	}
	return nil
}

type Players struct {
	Players              map[string]*Players_AbsolutePoint `protobuf:"bytes,1,rep,name=players,proto3" json:"players,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}                          `json:"-"`
	XXX_unrecognized     []byte                            `json:"-"`
	XXX_sizecache        int32                             `json:"-"`
}

func (m *Players) Reset()         { *m = Players{} }
func (m *Players) String() string { return proto.CompactTextString(m) }
func (*Players) ProtoMessage()    {}
func (*Players) Descriptor() ([]byte, []int) {
	return fileDescriptor_2c0f90c600ad7e2e, []int{2}
}

func (m *Players) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Players.Unmarshal(m, b)
}
func (m *Players) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Players.Marshal(b, m, deterministic)
}
func (m *Players) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Players.Merge(m, src)
}
func (m *Players) XXX_Size() int {
	return xxx_messageInfo_Players.Size(m)
}
func (m *Players) XXX_DiscardUnknown() {
	xxx_messageInfo_Players.DiscardUnknown(m)
}

var xxx_messageInfo_Players proto.InternalMessageInfo

func (m *Players) GetPlayers() map[string]*Players_AbsolutePoint {
	if m != nil {
		return m.Players
	}
	return nil
}

type Players_AbsolutePoint struct {
	ChunkX               int64    `protobuf:"varint,1,opt,name=chunkX,proto3" json:"chunkX,omitempty"`
	ChunkY               int64    `protobuf:"varint,2,opt,name=chunkY,proto3" json:"chunkY,omitempty"`
	ChunkZ               int64    `protobuf:"varint,3,opt,name=chunkZ,proto3" json:"chunkZ,omitempty"`
	VoxelX               uint32   `protobuf:"varint,4,opt,name=voxelX,proto3" json:"voxelX,omitempty"`
	VoxelY               uint32   `protobuf:"varint,5,opt,name=voxelY,proto3" json:"voxelY,omitempty"`
	VoxelZ               uint32   `protobuf:"varint,6,opt,name=voxelZ,proto3" json:"voxelZ,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Players_AbsolutePoint) Reset()         { *m = Players_AbsolutePoint{} }
func (m *Players_AbsolutePoint) String() string { return proto.CompactTextString(m) }
func (*Players_AbsolutePoint) ProtoMessage()    {}
func (*Players_AbsolutePoint) Descriptor() ([]byte, []int) {
	return fileDescriptor_2c0f90c600ad7e2e, []int{2, 0}
}

func (m *Players_AbsolutePoint) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Players_AbsolutePoint.Unmarshal(m, b)
}
func (m *Players_AbsolutePoint) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Players_AbsolutePoint.Marshal(b, m, deterministic)
}
func (m *Players_AbsolutePoint) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Players_AbsolutePoint.Merge(m, src)
}
func (m *Players_AbsolutePoint) XXX_Size() int {
	return xxx_messageInfo_Players_AbsolutePoint.Size(m)
}
func (m *Players_AbsolutePoint) XXX_DiscardUnknown() {
	xxx_messageInfo_Players_AbsolutePoint.DiscardUnknown(m)
}

var xxx_messageInfo_Players_AbsolutePoint proto.InternalMessageInfo

func (m *Players_AbsolutePoint) GetChunkX() int64 {
	if m != nil {
		return m.ChunkX
	}
	return 0
}

func (m *Players_AbsolutePoint) GetChunkY() int64 {
	if m != nil {
		return m.ChunkY
	}
	return 0
}

func (m *Players_AbsolutePoint) GetChunkZ() int64 {
	if m != nil {
		return m.ChunkZ
	}
	return 0
}

func (m *Players_AbsolutePoint) GetVoxelX() uint32 {
	if m != nil {
		return m.VoxelX
	}
	return 0
}

func (m *Players_AbsolutePoint) GetVoxelY() uint32 {
	if m != nil {
		return m.VoxelY
	}
	return 0
}

func (m *Players_AbsolutePoint) GetVoxelZ() uint32 {
	if m != nil {
		return m.VoxelZ
	}
	return 0
}

type Chunk struct {
	Voxels               *Chunk_Voxels              `protobuf:"bytes,1,opt,name=voxels,proto3" json:"voxels,omitempty"`
	Compound             map[uint32]*Chunk_Compound `protobuf:"bytes,2,rep,name=compound,proto3" json:"compound,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Entities             []*Chunk_EntityAtPoint     `protobuf:"bytes,3,rep,name=entities,proto3" json:"entities,omitempty"`
	Items                []*Chunk_ItemAtPoint       `protobuf:"bytes,4,rep,name=items,proto3" json:"items,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                   `json:"-"`
	XXX_unrecognized     []byte                     `json:"-"`
	XXX_sizecache        int32                      `json:"-"`
}

func (m *Chunk) Reset()         { *m = Chunk{} }
func (m *Chunk) String() string { return proto.CompactTextString(m) }
func (*Chunk) ProtoMessage()    {}
func (*Chunk) Descriptor() ([]byte, []int) {
	return fileDescriptor_2c0f90c600ad7e2e, []int{3}
}

func (m *Chunk) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Chunk.Unmarshal(m, b)
}
func (m *Chunk) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Chunk.Marshal(b, m, deterministic)
}
func (m *Chunk) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Chunk.Merge(m, src)
}
func (m *Chunk) XXX_Size() int {
	return xxx_messageInfo_Chunk.Size(m)
}
func (m *Chunk) XXX_DiscardUnknown() {
	xxx_messageInfo_Chunk.DiscardUnknown(m)
}

var xxx_messageInfo_Chunk proto.InternalMessageInfo

func (m *Chunk) GetVoxels() *Chunk_Voxels {
	if m != nil {
		return m.Voxels
	}
	return nil
}

func (m *Chunk) GetCompound() map[uint32]*Chunk_Compound {
	if m != nil {
		return m.Compound
	}
	return nil
}

func (m *Chunk) GetEntities() []*Chunk_EntityAtPoint {
	if m != nil {
		return m.Entities
	}
	return nil
}

func (m *Chunk) GetItems() []*Chunk_ItemAtPoint {
	if m != nil {
		return m.Items
	}
	return nil
}

type Chunk_Voxels struct {
	Planes               []*Chunk_Voxels_Plane `protobuf:"bytes,1,rep,name=planes,proto3" json:"planes,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *Chunk_Voxels) Reset()         { *m = Chunk_Voxels{} }
func (m *Chunk_Voxels) String() string { return proto.CompactTextString(m) }
func (*Chunk_Voxels) ProtoMessage()    {}
func (*Chunk_Voxels) Descriptor() ([]byte, []int) {
	return fileDescriptor_2c0f90c600ad7e2e, []int{3, 0}
}

func (m *Chunk_Voxels) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Chunk_Voxels.Unmarshal(m, b)
}
func (m *Chunk_Voxels) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Chunk_Voxels.Marshal(b, m, deterministic)
}
func (m *Chunk_Voxels) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Chunk_Voxels.Merge(m, src)
}
func (m *Chunk_Voxels) XXX_Size() int {
	return xxx_messageInfo_Chunk_Voxels.Size(m)
}
func (m *Chunk_Voxels) XXX_DiscardUnknown() {
	xxx_messageInfo_Chunk_Voxels.DiscardUnknown(m)
}

var xxx_messageInfo_Chunk_Voxels proto.InternalMessageInfo

func (m *Chunk_Voxels) GetPlanes() []*Chunk_Voxels_Plane {
	if m != nil {
		return m.Planes
	}
	return nil
}

type Chunk_Voxels_Plane struct {
	Rows                 []*Chunk_Voxels_Plane_Row `protobuf:"bytes,1,rep,name=rows,proto3" json:"rows,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                  `json:"-"`
	XXX_unrecognized     []byte                    `json:"-"`
	XXX_sizecache        int32                     `json:"-"`
}

func (m *Chunk_Voxels_Plane) Reset()         { *m = Chunk_Voxels_Plane{} }
func (m *Chunk_Voxels_Plane) String() string { return proto.CompactTextString(m) }
func (*Chunk_Voxels_Plane) ProtoMessage()    {}
func (*Chunk_Voxels_Plane) Descriptor() ([]byte, []int) {
	return fileDescriptor_2c0f90c600ad7e2e, []int{3, 0, 0}
}

func (m *Chunk_Voxels_Plane) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Chunk_Voxels_Plane.Unmarshal(m, b)
}
func (m *Chunk_Voxels_Plane) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Chunk_Voxels_Plane.Marshal(b, m, deterministic)
}
func (m *Chunk_Voxels_Plane) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Chunk_Voxels_Plane.Merge(m, src)
}
func (m *Chunk_Voxels_Plane) XXX_Size() int {
	return xxx_messageInfo_Chunk_Voxels_Plane.Size(m)
}
func (m *Chunk_Voxels_Plane) XXX_DiscardUnknown() {
	xxx_messageInfo_Chunk_Voxels_Plane.DiscardUnknown(m)
}

var xxx_messageInfo_Chunk_Voxels_Plane proto.InternalMessageInfo

func (m *Chunk_Voxels_Plane) GetRows() []*Chunk_Voxels_Plane_Row {
	if m != nil {
		return m.Rows
	}
	return nil
}

type Chunk_Voxels_Plane_Row struct {
	Voxel                []uint64 `protobuf:"varint,1,rep,packed,name=voxel,proto3" json:"voxel,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Chunk_Voxels_Plane_Row) Reset()         { *m = Chunk_Voxels_Plane_Row{} }
func (m *Chunk_Voxels_Plane_Row) String() string { return proto.CompactTextString(m) }
func (*Chunk_Voxels_Plane_Row) ProtoMessage()    {}
func (*Chunk_Voxels_Plane_Row) Descriptor() ([]byte, []int) {
	return fileDescriptor_2c0f90c600ad7e2e, []int{3, 0, 0, 0}
}

func (m *Chunk_Voxels_Plane_Row) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Chunk_Voxels_Plane_Row.Unmarshal(m, b)
}
func (m *Chunk_Voxels_Plane_Row) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Chunk_Voxels_Plane_Row.Marshal(b, m, deterministic)
}
func (m *Chunk_Voxels_Plane_Row) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Chunk_Voxels_Plane_Row.Merge(m, src)
}
func (m *Chunk_Voxels_Plane_Row) XXX_Size() int {
	return xxx_messageInfo_Chunk_Voxels_Plane_Row.Size(m)
}
func (m *Chunk_Voxels_Plane_Row) XXX_DiscardUnknown() {
	xxx_messageInfo_Chunk_Voxels_Plane_Row.DiscardUnknown(m)
}

var xxx_messageInfo_Chunk_Voxels_Plane_Row proto.InternalMessageInfo

func (m *Chunk_Voxels_Plane_Row) GetVoxel() []uint64 {
	if m != nil {
		return m.Voxel
	}
	return nil
}

type Chunk_Compound struct {
	Inventory            *Inventory    `protobuf:"bytes,1,opt,name=inventory,proto3" json:"inventory,omitempty"`
	Properties           *PrimitiveMap `protobuf:"bytes,2,opt,name=properties,proto3" json:"properties,omitempty"`
	MultiblockChunk      *Point        `protobuf:"bytes,3,opt,name=multiblockChunk,proto3" json:"multiblockChunk,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *Chunk_Compound) Reset()         { *m = Chunk_Compound{} }
func (m *Chunk_Compound) String() string { return proto.CompactTextString(m) }
func (*Chunk_Compound) ProtoMessage()    {}
func (*Chunk_Compound) Descriptor() ([]byte, []int) {
	return fileDescriptor_2c0f90c600ad7e2e, []int{3, 1}
}

func (m *Chunk_Compound) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Chunk_Compound.Unmarshal(m, b)
}
func (m *Chunk_Compound) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Chunk_Compound.Marshal(b, m, deterministic)
}
func (m *Chunk_Compound) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Chunk_Compound.Merge(m, src)
}
func (m *Chunk_Compound) XXX_Size() int {
	return xxx_messageInfo_Chunk_Compound.Size(m)
}
func (m *Chunk_Compound) XXX_DiscardUnknown() {
	xxx_messageInfo_Chunk_Compound.DiscardUnknown(m)
}

var xxx_messageInfo_Chunk_Compound proto.InternalMessageInfo

func (m *Chunk_Compound) GetInventory() *Inventory {
	if m != nil {
		return m.Inventory
	}
	return nil
}

func (m *Chunk_Compound) GetProperties() *PrimitiveMap {
	if m != nil {
		return m.Properties
	}
	return nil
}

func (m *Chunk_Compound) GetMultiblockChunk() *Point {
	if m != nil {
		return m.MultiblockChunk
	}
	return nil
}

type Chunk_EntityAtPoint struct {
	Point                *Point   `protobuf:"bytes,1,opt,name=point,proto3" json:"point,omitempty"`
	Entity               *Entity  `protobuf:"bytes,2,opt,name=entity,proto3" json:"entity,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Chunk_EntityAtPoint) Reset()         { *m = Chunk_EntityAtPoint{} }
func (m *Chunk_EntityAtPoint) String() string { return proto.CompactTextString(m) }
func (*Chunk_EntityAtPoint) ProtoMessage()    {}
func (*Chunk_EntityAtPoint) Descriptor() ([]byte, []int) {
	return fileDescriptor_2c0f90c600ad7e2e, []int{3, 3}
}

func (m *Chunk_EntityAtPoint) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Chunk_EntityAtPoint.Unmarshal(m, b)
}
func (m *Chunk_EntityAtPoint) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Chunk_EntityAtPoint.Marshal(b, m, deterministic)
}
func (m *Chunk_EntityAtPoint) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Chunk_EntityAtPoint.Merge(m, src)
}
func (m *Chunk_EntityAtPoint) XXX_Size() int {
	return xxx_messageInfo_Chunk_EntityAtPoint.Size(m)
}
func (m *Chunk_EntityAtPoint) XXX_DiscardUnknown() {
	xxx_messageInfo_Chunk_EntityAtPoint.DiscardUnknown(m)
}

var xxx_messageInfo_Chunk_EntityAtPoint proto.InternalMessageInfo

func (m *Chunk_EntityAtPoint) GetPoint() *Point {
	if m != nil {
		return m.Point
	}
	return nil
}

func (m *Chunk_EntityAtPoint) GetEntity() *Entity {
	if m != nil {
		return m.Entity
	}
	return nil
}

type Chunk_ItemAtPoint struct {
	Point                *Point   `protobuf:"bytes,1,opt,name=point,proto3" json:"point,omitempty"`
	Item                 *Item    `protobuf:"bytes,2,opt,name=item,proto3" json:"item,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Chunk_ItemAtPoint) Reset()         { *m = Chunk_ItemAtPoint{} }
func (m *Chunk_ItemAtPoint) String() string { return proto.CompactTextString(m) }
func (*Chunk_ItemAtPoint) ProtoMessage()    {}
func (*Chunk_ItemAtPoint) Descriptor() ([]byte, []int) {
	return fileDescriptor_2c0f90c600ad7e2e, []int{3, 4}
}

func (m *Chunk_ItemAtPoint) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Chunk_ItemAtPoint.Unmarshal(m, b)
}
func (m *Chunk_ItemAtPoint) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Chunk_ItemAtPoint.Marshal(b, m, deterministic)
}
func (m *Chunk_ItemAtPoint) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Chunk_ItemAtPoint.Merge(m, src)
}
func (m *Chunk_ItemAtPoint) XXX_Size() int {
	return xxx_messageInfo_Chunk_ItemAtPoint.Size(m)
}
func (m *Chunk_ItemAtPoint) XXX_DiscardUnknown() {
	xxx_messageInfo_Chunk_ItemAtPoint.DiscardUnknown(m)
}

var xxx_messageInfo_Chunk_ItemAtPoint proto.InternalMessageInfo

func (m *Chunk_ItemAtPoint) GetPoint() *Point {
	if m != nil {
		return m.Point
	}
	return nil
}

func (m *Chunk_ItemAtPoint) GetItem() *Item {
	if m != nil {
		return m.Item
	}
	return nil
}

type Inventory struct {
	Items                []*Item  `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Inventory) Reset()         { *m = Inventory{} }
func (m *Inventory) String() string { return proto.CompactTextString(m) }
func (*Inventory) ProtoMessage()    {}
func (*Inventory) Descriptor() ([]byte, []int) {
	return fileDescriptor_2c0f90c600ad7e2e, []int{4}
}

func (m *Inventory) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Inventory.Unmarshal(m, b)
}
func (m *Inventory) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Inventory.Marshal(b, m, deterministic)
}
func (m *Inventory) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Inventory.Merge(m, src)
}
func (m *Inventory) XXX_Size() int {
	return xxx_messageInfo_Inventory.Size(m)
}
func (m *Inventory) XXX_DiscardUnknown() {
	xxx_messageInfo_Inventory.DiscardUnknown(m)
}

var xxx_messageInfo_Inventory proto.InternalMessageInfo

func (m *Inventory) GetItems() []*Item {
	if m != nil {
		return m.Items
	}
	return nil
}

type Entity struct {
	Player               bool          `protobuf:"varint,1,opt,name=player,proto3" json:"player,omitempty"`
	Type                 uint32        `protobuf:"varint,2,opt,name=type,proto3" json:"type,omitempty"`
	Properties           *PrimitiveMap `protobuf:"bytes,3,opt,name=properties,proto3" json:"properties,omitempty"`
	Inventory            *Inventory    `protobuf:"bytes,4,opt,name=inventory,proto3" json:"inventory,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *Entity) Reset()         { *m = Entity{} }
func (m *Entity) String() string { return proto.CompactTextString(m) }
func (*Entity) ProtoMessage()    {}
func (*Entity) Descriptor() ([]byte, []int) {
	return fileDescriptor_2c0f90c600ad7e2e, []int{5}
}

func (m *Entity) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Entity.Unmarshal(m, b)
}
func (m *Entity) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Entity.Marshal(b, m, deterministic)
}
func (m *Entity) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Entity.Merge(m, src)
}
func (m *Entity) XXX_Size() int {
	return xxx_messageInfo_Entity.Size(m)
}
func (m *Entity) XXX_DiscardUnknown() {
	xxx_messageInfo_Entity.DiscardUnknown(m)
}

var xxx_messageInfo_Entity proto.InternalMessageInfo

func (m *Entity) GetPlayer() bool {
	if m != nil {
		return m.Player
	}
	return false
}

func (m *Entity) GetType() uint32 {
	if m != nil {
		return m.Type
	}
	return 0
}

func (m *Entity) GetProperties() *PrimitiveMap {
	if m != nil {
		return m.Properties
	}
	return nil
}

func (m *Entity) GetInventory() *Inventory {
	if m != nil {
		return m.Inventory
	}
	return nil
}

type Item struct {
	// Types that are valid to be assigned to Item:
	//	*Item_Simple
	//	*Item_Complex
	Item                 isItem_Item `protobuf_oneof:"item"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *Item) Reset()         { *m = Item{} }
func (m *Item) String() string { return proto.CompactTextString(m) }
func (*Item) ProtoMessage()    {}
func (*Item) Descriptor() ([]byte, []int) {
	return fileDescriptor_2c0f90c600ad7e2e, []int{6}
}

func (m *Item) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Item.Unmarshal(m, b)
}
func (m *Item) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Item.Marshal(b, m, deterministic)
}
func (m *Item) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Item.Merge(m, src)
}
func (m *Item) XXX_Size() int {
	return xxx_messageInfo_Item.Size(m)
}
func (m *Item) XXX_DiscardUnknown() {
	xxx_messageInfo_Item.DiscardUnknown(m)
}

var xxx_messageInfo_Item proto.InternalMessageInfo

type isItem_Item interface {
	isItem_Item()
}

type Item_Simple struct {
	Simple *Item_SimpleItem `protobuf:"bytes,1,opt,name=simple,proto3,oneof"`
}

type Item_Complex struct {
	Complex *Item_ComplexItem `protobuf:"bytes,2,opt,name=complex,proto3,oneof"`
}

func (*Item_Simple) isItem_Item() {}

func (*Item_Complex) isItem_Item() {}

func (m *Item) GetItem() isItem_Item {
	if m != nil {
		return m.Item
	}
	return nil
}

func (m *Item) GetSimple() *Item_SimpleItem {
	if x, ok := m.GetItem().(*Item_Simple); ok {
		return x.Simple
	}
	return nil
}

func (m *Item) GetComplex() *Item_ComplexItem {
	if x, ok := m.GetItem().(*Item_Complex); ok {
		return x.Complex
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*Item) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _Item_OneofMarshaler, _Item_OneofUnmarshaler, _Item_OneofSizer, []interface{}{
		(*Item_Simple)(nil),
		(*Item_Complex)(nil),
	}
}

func _Item_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*Item)
	// item
	switch x := m.Item.(type) {
	case *Item_Simple:
		b.EncodeVarint(1<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Simple); err != nil {
			return err
		}
	case *Item_Complex:
		b.EncodeVarint(2<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Complex); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("Item.Item has unexpected type %T", x)
	}
	return nil
}

func _Item_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*Item)
	switch tag {
	case 1: // item.simple
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(Item_SimpleItem)
		err := b.DecodeMessage(msg)
		m.Item = &Item_Simple{msg}
		return true, err
	case 2: // item.complex
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(Item_ComplexItem)
		err := b.DecodeMessage(msg)
		m.Item = &Item_Complex{msg}
		return true, err
	default:
		return false, nil
	}
}

func _Item_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*Item)
	// item
	switch x := m.Item.(type) {
	case *Item_Simple:
		s := proto.Size(x.Simple)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Item_Complex:
		s := proto.Size(x.Complex)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

type Item_SimpleItem struct {
	Form                 uint32        `protobuf:"varint,1,opt,name=form,proto3" json:"form,omitempty"`
	Material             uint32        `protobuf:"varint,2,opt,name=material,proto3" json:"material,omitempty"`
	Properties           *PrimitiveMap `protobuf:"bytes,3,opt,name=properties,proto3" json:"properties,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *Item_SimpleItem) Reset()         { *m = Item_SimpleItem{} }
func (m *Item_SimpleItem) String() string { return proto.CompactTextString(m) }
func (*Item_SimpleItem) ProtoMessage()    {}
func (*Item_SimpleItem) Descriptor() ([]byte, []int) {
	return fileDescriptor_2c0f90c600ad7e2e, []int{6, 0}
}

func (m *Item_SimpleItem) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Item_SimpleItem.Unmarshal(m, b)
}
func (m *Item_SimpleItem) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Item_SimpleItem.Marshal(b, m, deterministic)
}
func (m *Item_SimpleItem) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Item_SimpleItem.Merge(m, src)
}
func (m *Item_SimpleItem) XXX_Size() int {
	return xxx_messageInfo_Item_SimpleItem.Size(m)
}
func (m *Item_SimpleItem) XXX_DiscardUnknown() {
	xxx_messageInfo_Item_SimpleItem.DiscardUnknown(m)
}

var xxx_messageInfo_Item_SimpleItem proto.InternalMessageInfo

func (m *Item_SimpleItem) GetForm() uint32 {
	if m != nil {
		return m.Form
	}
	return 0
}

func (m *Item_SimpleItem) GetMaterial() uint32 {
	if m != nil {
		return m.Material
	}
	return 0
}

func (m *Item_SimpleItem) GetProperties() *PrimitiveMap {
	if m != nil {
		return m.Properties
	}
	return nil
}

type Item_ComplexItem struct {
	Form                 uint32        `protobuf:"varint,1,opt,name=form,proto3" json:"form,omitempty"`
	Components           []*Item       `protobuf:"bytes,2,rep,name=components,proto3" json:"components,omitempty"`
	Properties           *PrimitiveMap `protobuf:"bytes,3,opt,name=properties,proto3" json:"properties,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *Item_ComplexItem) Reset()         { *m = Item_ComplexItem{} }
func (m *Item_ComplexItem) String() string { return proto.CompactTextString(m) }
func (*Item_ComplexItem) ProtoMessage()    {}
func (*Item_ComplexItem) Descriptor() ([]byte, []int) {
	return fileDescriptor_2c0f90c600ad7e2e, []int{6, 1}
}

func (m *Item_ComplexItem) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Item_ComplexItem.Unmarshal(m, b)
}
func (m *Item_ComplexItem) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Item_ComplexItem.Marshal(b, m, deterministic)
}
func (m *Item_ComplexItem) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Item_ComplexItem.Merge(m, src)
}
func (m *Item_ComplexItem) XXX_Size() int {
	return xxx_messageInfo_Item_ComplexItem.Size(m)
}
func (m *Item_ComplexItem) XXX_DiscardUnknown() {
	xxx_messageInfo_Item_ComplexItem.DiscardUnknown(m)
}

var xxx_messageInfo_Item_ComplexItem proto.InternalMessageInfo

func (m *Item_ComplexItem) GetForm() uint32 {
	if m != nil {
		return m.Form
	}
	return 0
}

func (m *Item_ComplexItem) GetComponents() []*Item {
	if m != nil {
		return m.Components
	}
	return nil
}

func (m *Item_ComplexItem) GetProperties() *PrimitiveMap {
	if m != nil {
		return m.Properties
	}
	return nil
}

type Point struct {
	X                    int64    `protobuf:"varint,1,opt,name=x,proto3" json:"x,omitempty"`
	Y                    int64    `protobuf:"varint,2,opt,name=y,proto3" json:"y,omitempty"`
	Z                    int64    `protobuf:"varint,3,opt,name=z,proto3" json:"z,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Point) Reset()         { *m = Point{} }
func (m *Point) String() string { return proto.CompactTextString(m) }
func (*Point) ProtoMessage()    {}
func (*Point) Descriptor() ([]byte, []int) {
	return fileDescriptor_2c0f90c600ad7e2e, []int{7}
}

func (m *Point) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Point.Unmarshal(m, b)
}
func (m *Point) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Point.Marshal(b, m, deterministic)
}
func (m *Point) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Point.Merge(m, src)
}
func (m *Point) XXX_Size() int {
	return xxx_messageInfo_Point.Size(m)
}
func (m *Point) XXX_DiscardUnknown() {
	xxx_messageInfo_Point.DiscardUnknown(m)
}

var xxx_messageInfo_Point proto.InternalMessageInfo

func (m *Point) GetX() int64 {
	if m != nil {
		return m.X
	}
	return 0
}

func (m *Point) GetY() int64 {
	if m != nil {
		return m.Y
	}
	return 0
}

func (m *Point) GetZ() int64 {
	if m != nil {
		return m.Z
	}
	return 0
}

type PrimitiveMap struct {
	Map                  map[string]*Primitive `protobuf:"bytes,1,rep,name=map,proto3" json:"map,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *PrimitiveMap) Reset()         { *m = PrimitiveMap{} }
func (m *PrimitiveMap) String() string { return proto.CompactTextString(m) }
func (*PrimitiveMap) ProtoMessage()    {}
func (*PrimitiveMap) Descriptor() ([]byte, []int) {
	return fileDescriptor_2c0f90c600ad7e2e, []int{8}
}

func (m *PrimitiveMap) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PrimitiveMap.Unmarshal(m, b)
}
func (m *PrimitiveMap) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PrimitiveMap.Marshal(b, m, deterministic)
}
func (m *PrimitiveMap) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PrimitiveMap.Merge(m, src)
}
func (m *PrimitiveMap) XXX_Size() int {
	return xxx_messageInfo_PrimitiveMap.Size(m)
}
func (m *PrimitiveMap) XXX_DiscardUnknown() {
	xxx_messageInfo_PrimitiveMap.DiscardUnknown(m)
}

var xxx_messageInfo_PrimitiveMap proto.InternalMessageInfo

func (m *PrimitiveMap) GetMap() map[string]*Primitive {
	if m != nil {
		return m.Map
	}
	return nil
}

type Primitive struct {
	// Types that are valid to be assigned to Value:
	//	*Primitive_String_
	//	*Primitive_Int
	//	*Primitive_Bool
	//	*Primitive_Float
	Value                isPrimitive_Value `protobuf_oneof:"value"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Primitive) Reset()         { *m = Primitive{} }
func (m *Primitive) String() string { return proto.CompactTextString(m) }
func (*Primitive) ProtoMessage()    {}
func (*Primitive) Descriptor() ([]byte, []int) {
	return fileDescriptor_2c0f90c600ad7e2e, []int{9}
}

func (m *Primitive) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Primitive.Unmarshal(m, b)
}
func (m *Primitive) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Primitive.Marshal(b, m, deterministic)
}
func (m *Primitive) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Primitive.Merge(m, src)
}
func (m *Primitive) XXX_Size() int {
	return xxx_messageInfo_Primitive.Size(m)
}
func (m *Primitive) XXX_DiscardUnknown() {
	xxx_messageInfo_Primitive.DiscardUnknown(m)
}

var xxx_messageInfo_Primitive proto.InternalMessageInfo

type isPrimitive_Value interface {
	isPrimitive_Value()
}

type Primitive_String_ struct {
	String_ string `protobuf:"bytes,1,opt,name=string,proto3,oneof"`
}

type Primitive_Int struct {
	Int int64 `protobuf:"varint,2,opt,name=int,proto3,oneof"`
}

type Primitive_Bool struct {
	Bool bool `protobuf:"varint,3,opt,name=bool,proto3,oneof"`
}

type Primitive_Float struct {
	Float float32 `protobuf:"fixed32,4,opt,name=float,proto3,oneof"`
}

func (*Primitive_String_) isPrimitive_Value() {}

func (*Primitive_Int) isPrimitive_Value() {}

func (*Primitive_Bool) isPrimitive_Value() {}

func (*Primitive_Float) isPrimitive_Value() {}

func (m *Primitive) GetValue() isPrimitive_Value {
	if m != nil {
		return m.Value
	}
	return nil
}

func (m *Primitive) GetString_() string {
	if x, ok := m.GetValue().(*Primitive_String_); ok {
		return x.String_
	}
	return ""
}

func (m *Primitive) GetInt() int64 {
	if x, ok := m.GetValue().(*Primitive_Int); ok {
		return x.Int
	}
	return 0
}

func (m *Primitive) GetBool() bool {
	if x, ok := m.GetValue().(*Primitive_Bool); ok {
		return x.Bool
	}
	return false
}

func (m *Primitive) GetFloat() float32 {
	if x, ok := m.GetValue().(*Primitive_Float); ok {
		return x.Float
	}
	return 0
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*Primitive) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _Primitive_OneofMarshaler, _Primitive_OneofUnmarshaler, _Primitive_OneofSizer, []interface{}{
		(*Primitive_String_)(nil),
		(*Primitive_Int)(nil),
		(*Primitive_Bool)(nil),
		(*Primitive_Float)(nil),
	}
}

func _Primitive_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*Primitive)
	// value
	switch x := m.Value.(type) {
	case *Primitive_String_:
		b.EncodeVarint(1<<3 | proto.WireBytes)
		b.EncodeStringBytes(x.String_)
	case *Primitive_Int:
		b.EncodeVarint(2<<3 | proto.WireVarint)
		b.EncodeVarint(uint64(x.Int))
	case *Primitive_Bool:
		t := uint64(0)
		if x.Bool {
			t = 1
		}
		b.EncodeVarint(3<<3 | proto.WireVarint)
		b.EncodeVarint(t)
	case *Primitive_Float:
		b.EncodeVarint(4<<3 | proto.WireFixed32)
		b.EncodeFixed32(uint64(math.Float32bits(x.Float)))
	case nil:
	default:
		return fmt.Errorf("Primitive.Value has unexpected type %T", x)
	}
	return nil
}

func _Primitive_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*Primitive)
	switch tag {
	case 1: // value.string
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeStringBytes()
		m.Value = &Primitive_String_{x}
		return true, err
	case 2: // value.int
		if wire != proto.WireVarint {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeVarint()
		m.Value = &Primitive_Int{int64(x)}
		return true, err
	case 3: // value.bool
		if wire != proto.WireVarint {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeVarint()
		m.Value = &Primitive_Bool{x != 0}
		return true, err
	case 4: // value.float
		if wire != proto.WireFixed32 {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeFixed32()
		m.Value = &Primitive_Float{math.Float32frombits(uint32(x))}
		return true, err
	default:
		return false, nil
	}
}

func _Primitive_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*Primitive)
	// value
	switch x := m.Value.(type) {
	case *Primitive_String_:
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(len(x.String_)))
		n += len(x.String_)
	case *Primitive_Int:
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(x.Int))
	case *Primitive_Bool:
		n += 1 // tag and wire
		n += 1
	case *Primitive_Float:
		n += 1 // tag and wire
		n += 4
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

type Nothing struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Nothing) Reset()         { *m = Nothing{} }
func (m *Nothing) String() string { return proto.CompactTextString(m) }
func (*Nothing) ProtoMessage()    {}
func (*Nothing) Descriptor() ([]byte, []int) {
	return fileDescriptor_2c0f90c600ad7e2e, []int{10}
}

func (m *Nothing) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Nothing.Unmarshal(m, b)
}
func (m *Nothing) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Nothing.Marshal(b, m, deterministic)
}
func (m *Nothing) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Nothing.Merge(m, src)
}
func (m *Nothing) XXX_Size() int {
	return xxx_messageInfo_Nothing.Size(m)
}
func (m *Nothing) XXX_DiscardUnknown() {
	xxx_messageInfo_Nothing.DiscardUnknown(m)
}

var xxx_messageInfo_Nothing proto.InternalMessageInfo

func init() {
	proto.RegisterType((*Age)(nil), "Age")
	proto.RegisterType((*Config)(nil), "Config")
	proto.RegisterType((*Players)(nil), "Players")
	proto.RegisterMapType((map[string]*Players_AbsolutePoint)(nil), "Players.PlayersEntry")
	proto.RegisterType((*Players_AbsolutePoint)(nil), "Players.AbsolutePoint")
	proto.RegisterType((*Chunk)(nil), "Chunk")
	proto.RegisterMapType((map[uint32]*Chunk_Compound)(nil), "Chunk.CompoundEntry")
	proto.RegisterType((*Chunk_Voxels)(nil), "Chunk.Voxels")
	proto.RegisterType((*Chunk_Voxels_Plane)(nil), "Chunk.Voxels.Plane")
	proto.RegisterType((*Chunk_Voxels_Plane_Row)(nil), "Chunk.Voxels.Plane.Row")
	proto.RegisterType((*Chunk_Compound)(nil), "Chunk.Compound")
	proto.RegisterType((*Chunk_EntityAtPoint)(nil), "Chunk.EntityAtPoint")
	proto.RegisterType((*Chunk_ItemAtPoint)(nil), "Chunk.ItemAtPoint")
	proto.RegisterType((*Inventory)(nil), "Inventory")
	proto.RegisterType((*Entity)(nil), "Entity")
	proto.RegisterType((*Item)(nil), "Item")
	proto.RegisterType((*Item_SimpleItem)(nil), "Item.SimpleItem")
	proto.RegisterType((*Item_ComplexItem)(nil), "Item.ComplexItem")
	proto.RegisterType((*Point)(nil), "Point")
	proto.RegisterType((*PrimitiveMap)(nil), "PrimitiveMap")
	proto.RegisterMapType((map[string]*Primitive)(nil), "PrimitiveMap.MapEntry")
	proto.RegisterType((*Primitive)(nil), "Primitive")
	proto.RegisterType((*Nothing)(nil), "Nothing")
}

func init() { proto.RegisterFile("types/types.proto", fileDescriptor_2c0f90c600ad7e2e) }

var fileDescriptor_2c0f90c600ad7e2e = []byte{
	// 848 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x55, 0xcd, 0x6e, 0xdb, 0x46,
	0x10, 0x36, 0xc5, 0x1f, 0x49, 0x23, 0x0b, 0x49, 0xb6, 0xae, 0xcb, 0xd2, 0x05, 0x6a, 0x10, 0x30,
	0x2a, 0x34, 0x0d, 0x93, 0xb8, 0x97, 0xa2, 0x37, 0xdb, 0x48, 0xe1, 0x00, 0x4d, 0xe0, 0x6e, 0x81,
	0x22, 0xd6, 0x8d, 0x52, 0xd7, 0xca, 0x42, 0x24, 0x97, 0x20, 0x57, 0x3f, 0x0c, 0xfa, 0x00, 0xbd,
	0xf4, 0xd8, 0x73, 0x5f, 0xa1, 0x2f, 0xd1, 0x73, 0x5f, 0xa9, 0xd8, 0xd9, 0x25, 0x45, 0x1a, 0x42,
	0x03, 0x5f, 0xec, 0x9d, 0x8f, 0xdf, 0xee, 0x7e, 0x33, 0xf3, 0xed, 0x08, 0x9e, 0xc8, 0x2a, 0x67,
	0xe5, 0x73, 0xfc, 0x1b, 0xe5, 0x85, 0x90, 0x22, 0x3c, 0x01, 0xfb, 0x62, 0xc1, 0xc8, 0x11, 0xb8,
	0x92, 0xcf, 0x97, 0xa5, 0x6f, 0x9d, 0x5a, 0x13, 0x87, 0xea, 0x20, 0x7c, 0x09, 0xde, 0x95, 0xc8,
	0xee, 0xf8, 0x82, 0x7c, 0x05, 0x7d, 0x91, 0x4b, 0x2e, 0x32, 0xcd, 0x18, 0x9d, 0x8f, 0xa3, 0x9b,
	0x82, 0xa7, 0x5c, 0xf2, 0x35, 0x7b, 0x13, 0xe7, 0xb4, 0xfe, 0x1a, 0xfe, 0xdd, 0x83, 0xfe, 0x4d,
	0x12, 0x57, 0xac, 0x28, 0xc9, 0x73, 0xe8, 0xe7, 0x7a, 0xe9, 0x5b, 0xa7, 0xf6, 0x64, 0x74, 0xfe,
	0x69, 0x64, 0x3e, 0xd5, 0xff, 0x5f, 0x65, 0xb2, 0xa8, 0x68, 0xcd, 0x0a, 0xfe, 0xb2, 0x60, 0x7c,
	0x31, 0x2b, 0x45, 0xb2, 0x92, 0xec, 0x46, 0xf0, 0x4c, 0x92, 0x63, 0xf0, 0xe6, 0xef, 0x57, 0xd9,
	0xf2, 0x1d, 0x5e, 0x6b, 0x53, 0x13, 0x35, 0xf8, 0xad, 0xdf, 0x6b, 0xe1, 0xb7, 0x0d, 0x3e, 0xf5,
	0xed, 0x16, 0x3e, 0x55, 0xf8, 0x5a, 0x6c, 0x59, 0xf2, 0xce, 0x77, 0x4e, 0xad, 0xc9, 0x98, 0x9a,
	0xa8, 0xc1, 0x6f, 0x7d, 0xb7, 0x85, 0xdf, 0x36, 0xf8, 0xd4, 0xf7, 0x5a, 0xf8, 0x34, 0xa0, 0x70,
	0xd8, 0x96, 0x4e, 0x1e, 0x83, 0xbd, 0x64, 0x15, 0x8a, 0x1b, 0x52, 0xb5, 0x24, 0xdf, 0x80, 0xbb,
	0x8e, 0x93, 0x15, 0x43, 0x61, 0xa3, 0xf3, 0xe3, 0x26, 0xe5, 0x4e, 0x62, 0x54, 0x93, 0xbe, 0xef,
	0x7d, 0x67, 0x85, 0xff, 0xb8, 0xe0, 0x5e, 0x29, 0x99, 0xe4, 0xcc, 0xdc, 0xba, 0x2b, 0x32, 0xe2,
	0xd1, 0x2f, 0x08, 0x1a, 0x11, 0x25, 0x79, 0x01, 0x83, 0xb9, 0x48, 0x73, 0xb1, 0xca, 0x7e, 0xf5,
	0x7b, 0x58, 0xd8, 0x23, 0x43, 0xbc, 0x32, 0xb0, 0xae, 0x6b, 0xc3, 0x52, 0x3b, 0x58, 0x26, 0xb9,
	0xe4, 0xac, 0xf4, 0xed, 0xce, 0x8e, 0x57, 0x0a, 0xae, 0x2e, 0xa4, 0x56, 0xd5, 0xb0, 0xc8, 0x04,
	0x5c, 0x2e, 0x59, 0x5a, 0xfa, 0x0e, 0xd2, 0x89, 0xa1, 0xbf, 0x96, 0x2c, 0xad, 0xc9, 0x9a, 0x10,
	0xfc, 0x6e, 0x81, 0xa7, 0x05, 0x92, 0xa7, 0xe0, 0xe5, 0x49, 0x9c, 0xb1, 0xba, 0xdf, 0x9f, 0x74,
	0xf4, 0xab, 0x4a, 0x64, 0x8c, 0x1a, 0x4a, 0xf0, 0x13, 0xb8, 0x08, 0x90, 0xa7, 0xe0, 0x14, 0x62,
	0x53, 0xef, 0xf9, 0x6c, 0xcf, 0x9e, 0x88, 0x8a, 0x0d, 0x45, 0x52, 0x70, 0x02, 0x36, 0x15, 0x1b,
	0xe5, 0x57, 0x2c, 0x06, 0x6e, 0x72, 0xa8, 0x0e, 0x82, 0x3f, 0x2d, 0x18, 0xd4, 0x25, 0x20, 0x13,
	0x18, 0xf2, 0x6c, 0xcd, 0x32, 0x29, 0x8a, 0xca, 0xd4, 0x13, 0xa2, 0xd7, 0x35, 0x42, 0x77, 0x1f,
	0xc9, 0x33, 0x80, 0xbc, 0x10, 0x39, 0x2b, 0xb0, 0x3e, 0xbd, 0x7d, 0xfe, 0x6e, 0x11, 0xc8, 0x0b,
	0x78, 0x94, 0xae, 0x12, 0xc9, 0x67, 0x89, 0x98, 0x2f, 0x51, 0x2c, 0x9a, 0x6d, 0x74, 0xee, 0x45,
	0xba, 0x30, 0xf7, 0x3f, 0x07, 0x3f, 0xc2, 0xb8, 0xd3, 0x99, 0xb6, 0x6d, 0xc6, 0xda, 0x36, 0x67,
	0x5d, 0xdb, 0x3c, 0xba, 0xd7, 0xd0, 0x96, 0x5f, 0x82, 0xb7, 0x30, 0xee, 0x74, 0x8d, 0x7c, 0x01,
	0x6e, 0xae, 0x16, 0x26, 0xcb, 0x5a, 0x86, 0x06, 0xc9, 0x97, 0xe0, 0x61, 0x57, 0x2b, 0x73, 0x74,
	0xdf, 0xf4, 0x9c, 0x1a, 0x38, 0xf8, 0x01, 0x46, 0xad, 0xb6, 0x7e, 0xe4, 0xb4, 0xcf, 0xc1, 0x51,
	0x6d, 0x37, 0x67, 0xb9, 0x68, 0x08, 0x8a, 0x50, 0x38, 0x81, 0x61, 0x53, 0x5e, 0x72, 0x52, 0xfb,
	0x47, 0x77, 0xd5, 0x10, 0x35, 0x16, 0xfe, 0x61, 0x81, 0xa7, 0x45, 0xa8, 0x87, 0xa6, 0x5f, 0x3f,
	0x5e, 0x37, 0xa0, 0x26, 0x22, 0x04, 0x1c, 0x35, 0xa6, 0xf0, 0x9e, 0x31, 0xc5, 0xf5, 0xbd, 0x3e,
	0xd9, 0x1f, 0xeb, 0x53, 0xc7, 0x00, 0xce, 0xff, 0x18, 0x20, 0xfc, 0xb7, 0x07, 0x8e, 0xd2, 0x47,
	0xbe, 0x06, 0xaf, 0xe4, 0x69, 0x9e, 0x30, 0x93, 0xfc, 0x63, 0x94, 0x1d, 0xfd, 0x8c, 0x98, 0x5a,
	0x5e, 0x1f, 0x50, 0xc3, 0x20, 0xcf, 0xa0, 0xaf, 0xde, 0x57, 0xc2, 0xb6, 0xa6, 0x18, 0x4f, 0x34,
	0xf9, 0x4a, 0x83, 0x86, 0x5d, 0x73, 0x82, 0x25, 0xc0, 0xee, 0x18, 0x95, 0xde, 0x9d, 0x28, 0x52,
	0xe3, 0x00, 0x5c, 0x93, 0x00, 0x06, 0x69, 0x2c, 0x59, 0xc1, 0xe3, 0xc4, 0xa4, 0xdd, 0xc4, 0x0f,
	0x4c, 0x3d, 0xd8, 0xc0, 0xa8, 0x25, 0x63, 0xef, 0x6d, 0x67, 0x00, 0x38, 0x1e, 0x32, 0x96, 0xc9,
	0xd2, 0x8c, 0x11, 0xd3, 0xa5, 0xd6, 0x87, 0x07, 0x5e, 0x7c, 0xe9, 0x69, 0x7b, 0x84, 0x2f, 0xc1,
	0xd5, 0x6e, 0x3a, 0x04, 0x6b, 0x6b, 0x66, 0xb7, 0xb5, 0x55, 0x51, 0x65, 0x26, 0xb6, 0x55, 0xa9,
	0xe8, 0x83, 0x99, 0xd3, 0xd6, 0x87, 0xf0, 0x37, 0x38, 0x6c, 0x1f, 0x4b, 0x26, 0x60, 0xa7, 0x71,
	0x6e, 0xfc, 0x73, 0xdc, 0xb9, 0x32, 0x7a, 0x13, 0xe7, 0x7a, 0xc4, 0x29, 0x4a, 0x70, 0x09, 0x83,
	0x1a, 0xd8, 0x33, 0x90, 0x4f, 0xbb, 0x2f, 0x0b, 0x76, 0x27, 0xb5, 0x87, 0x70, 0x0e, 0xc3, 0x06,
	0x27, 0x3e, 0x78, 0xa5, 0x2c, 0x78, 0xb6, 0xd0, 0xe7, 0x60, 0xd3, 0x31, 0x26, 0x04, 0x6c, 0xf5,
	0x34, 0x30, 0x85, 0xeb, 0x03, 0xaa, 0x02, 0x72, 0x04, 0xce, 0x4c, 0x88, 0x04, 0x33, 0x19, 0x5c,
	0x1f, 0x50, 0x8c, 0xc8, 0x31, 0xb8, 0x77, 0x89, 0x88, 0x25, 0x3a, 0xaf, 0x77, 0x7d, 0x40, 0x75,
	0x78, 0xd9, 0x37, 0x72, 0xc2, 0x21, 0xf4, 0xdf, 0x0a, 0xf9, 0x9e, 0x67, 0x8b, 0x99, 0x87, 0xbf,
	0xc5, 0xdf, 0xfe, 0x17, 0x00, 0x00, 0xff, 0xff, 0x5e, 0xab, 0x34, 0x0b, 0xa0, 0x07, 0x00, 0x00,
}
